---
title: "Books and Resources for 431"
---

### Two Books you should purchase as soon as possible

We'll read two books this semester that you'll need to purchase (combined price is between \$18 and \$33):

- David Spiegelhater *The Art of Statistics: How to Learn from Data*, published in the US by Basic Books in 2019, available [at Amazon, for instance](https://www.amazon.com/Art-Statistics-How-Learn-Data/dp/1541618513), for around \$18 (Kindle) or \$23 (hardcover). 
    - From [Dr. Spiegelhalter's website](http://www.statslab.cam.ac.uk/~david/): *The Art of Statistics* is a Pelican book published by Penguin in March 2019 in the UK, and by Basic Books in the US in September 2019: the books are identical apart from the subtitle (the UK subtitle is *Learning from Data*) and cover. The UK Pelican paperback was published in February 2020.
    - The [book's website](https://dspiegel29.github.io/ArtofStatistics/) contains R code, corrections and other materials.
- Jeffrey Leek, *The Elements of Data Analytic Style*, available at https://leanpub.com/datastyle (minimum price is free, suggested price is $10).

Everything else that you will need is free, and will be described in detail on the permanent website once the class begins. Some highlights follow...

### Three Books you should download at your next opportunity

There are three additional free books that you will definitely need to obtain during the semester and may be interested in looking at before class begins. All are freely available to you, at the links below.

1. [R for Data Science](https://r4ds.had.co.nz/) by Garrett Grolemund and Hadley Wickham.
2. [Biostatistics for Biomedical Research](http://hbiostat.org/doc/bbr.pdf) (pdf) by Frank E. Harrell Jr and James C Slaughter. This is regularly updated by the authors, so get the most recent version occasionally.
3. [Modern Dive: Statistical Inference via Data Science (A Modern Dive into R and the Tidyverse)](https://moderndive.com) by Chester Ismay and Albert Y. Kim.

### Professor Love's Materials will be available later this month

The main text is a set of Notes for the course, maintained by Professor Love, titled **Data Science for Biological, Medical and Health Research: Notes for PQHS 431.** A link to these notes will be made available to you at the first class. Professor Love revises the Notes annually, and so they will appear in fits and starts as the semester progresses.

Although these Notes share some of the features of a textbook, they are neither comprehensive nor completely original. The main purpose is to give 431 students a set of common materials on which to draw during the course, providing a series of examples using R to work through issues that are likely to come up during the semester, and in later work. The notes are permanently a work in progress, and updates occur irregularly throughout the semester.

In addition, **slides** and video recordings from each of Professor Love's lectures, plus other in-class materials from each session of the class will be posted in a timely fashion on the main course website.

